# Generated by Django 5.0.4 on 2024-04-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationApp', '0003_people_reg_delete_geeksmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People_reg',
            new_name='PeopleReg',
        ),
    ]
